# Generated by Django 5.2.4 on 2025-07-12 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, unique=True), max_length=100),
        ),
    ]
